### ISSUE TITLE
GitHub Action Build fails 

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-dashboard-v2#8]
https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/runs/759987620?check_suite_focus=true

Failing on the packaging step which is odd as underlying dependencies did not change

**Comment by karianna** [comment]
@adam-thorpe Can you check if this is OK now?

**Comment by adam-thorpe** [comment]
@karianna can you kick off a new build as I don't have the perms to. Seems to work just fine locally though

**Comment by karianna** [comment]
I've got the same build error locally after npm clean, then npm install

```
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/favicon.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
🚨  Cannot read property 'length' of undefined
    at lineCounter (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:250:5)
    at async Bundle._package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Promise.all (index 2)
    at async Bundle.package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Bundler.bundle (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundler.js:325:27)
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/favicon.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
```

**Comment by karianna** [comment]
I also note our packages are quite far behind:

MININT-7P275HC:openjdk-dashboard-v2 karianna$ ncu
Checking /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/package.json
[====================] 15/15 100%

 antd                                      ^3.26.6  →    ^4.3.4
 highcharts                                 ^8.0.0  →    ^8.1.2
 highcharts-react-official                  ^2.2.2  →    ^3.0.0
 http-proxy-middleware                     ^0.19.0  →    ^1.0.4
 moment                                    ^2.24.0  →   ^2.26.0
 react                                    ^16.12.0  →  ^16.13.1
 react-dom                                ^16.12.0  →  ^16.13.1
 react-router                               ^5.1.2  →    ^5.2.0
 react-router-dom                           ^5.1.2  →    ^5.2.0
 @babel/core                                ^7.8.3  →   ^7.10.2
 @babel/plugin-proposal-class-properties    ^7.8.3  →   ^7.10.1

Run ncu -u to upgrade package.json

**Comment by adam-thorpe** [comment]
Perhaps I'm using some new functionality, all of packages are up to date

**Comment by karianna** [comment]
@adam-thorpe so when I run:

`npm clean-install` and then `npm start` I get:

```
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/index.js". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) falling back to RawAsset
🚨  Cannot read property 'length' of undefined
    at lineCounter (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:250:5)
    at async Bundle._package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Promise.all (index 2)
    at async Bundle.package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Bundler.bundle (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundler.js:325:27)
```

Same error regardless of whether I upgrade packages or not.

GitHub action build has a similar error.

I'm on Mac OS X 10.15.5 on npm 6.14.5 and ncu 7.0.1 and node 14.4.0

**Comment by adam-thorpe** [comment]
Ok I'm a bit behind on a few things. Mac OS X 10.15.5 npm 6.13.4 node 12.14.1. I'll try manually update all of those

**Comment by adam-thorpe** [comment]
Updating to node 14.4.0 replicated the failure.. I'll investigate

**Comment by adam-thorpe** [comment]
Removing the node_modules and package-lock.json and regenerating them with `npm install` fixes the problem, since it forcefully updates a bunch of the dependencies

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/runs/785230989 from latest run

**Comment by adam-thorpe** [comment]
See: https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/pull/12 for my latest changes. This worked when I did `npm install; npm start` and deleted dir, re-downloaded and did the same again  so hopefully it's re-building everything :/ I'm not an expert with node

**Comment by karianna** [comment]
I still get an error locally:

```
  Cannot read property 'length' of undefined
    at lineCounter (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:250:5)
    at async Bundle._package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Promise.all (index 2)
    at async Bundle.package (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Bundler.bundle (/Users/karianna/Documents/workspace/adoptopenjdk/openjdk-dashboard-v2/node_modules/parcel-bundler/src/Bundler.js:325:27)
```

**Comment by adam-thorpe** [comment]
Try do an `npm clean-install` ?

**Comment by karianna** [comment]
Yep, same issue sadly.

Cheers,
Martijn

**Comment by adam-thorpe** [comment]
The latest github build ran cleanly so may be something your end? I remember seeing that particular error but can't remember how I fixed it.. Maybe try removing node_modules or the entire repo and `npm install` again?

**Comment by karianna** [comment]
I'll have to keep debugging locally.  In the meantime does that mean the original change has now landed/been deployed?

**Comment by adam-thorpe** [comment]
Ah yes they are, thanks :)
